# Generated by Django 5.2.16 on 2026-07-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute'),
        ),
    ]
