# Generated by Django 5.2.16 on 2026-07-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_attribute_slug_attributevalue_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='slug',
            field=models.SlugField(default=' ', max_length=254),
            preserve_default=False,
        ),
    ]
